AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS-Serverless-Project

Parameters:
  LambdaRole:
    Type: String
    Default: arn:aws:iam::821383200340:role/AWS-Serverless-KatiMitja

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_user.create_item
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update_user.update_item
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active
      Events:
        UpdateUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: put

  RetrieveUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: retrieve_user.retrieve_user
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active
      Events:
        RetrieveUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get


  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete_user.delete_user
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: delete

  CreateEventBridge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_eventbridge.create_eventbridge
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active
      Events:
        RetrieveUser:
          Type: Api
          Properties:
            Path: /event
            Method: post

  GetCovidData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_covid_data.get_covid_data
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active

  GetWeatherData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_weather_data.get_weather_data
      Role: !Ref LambdaRole
      Runtime: python3.8
      Tracing: Active

  SendSES:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: src/
        Handler: send_ses.send_ses
        Role: !Ref LambdaRole
        Runtime: python3.8
        Tracing: Active

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: 'userdata'
      Tags:
        - Key: Owner
          Value: Kati
